### ISSUE TITLE
Have you chosen a License for your code?

### ISSUE THREAD

**Issue by kevinhendricks** [lagner/QGumboParser#1]
I was wondering if you had chosen a license for your code yet?  The Sigil open source GPL3 eBook Editor (uses Qt) is moving to incorporating google's gumbo parser to help support epub3.  I was going to wrapper the gumbo nodes into a DOM like structure (possibly QDom) and found your wrapper implementation when looking for other open source projects using gumbo.  But without a compatible license we won't be able to use it.

Thanks,
Kevin

**Comment by lagner** [comment]
Hi, Kevin. I added MIT license. I hope it is suitable for you. So feel free to use this code.
