### ISSUE TITLE
Getting the OuterHTML

### ISSUE THREAD

**Issue by RachidTagzen** [lagner/QGumboParser#5]
Hi,

How can I get the OuterHTML (not just the InnerText) of a specific Tag.
For example, If I want to get the **div** tag with **class="content"** from this HTML source:

```
<html>

   <head>
      <title>My Title</title>
      <meta content="">
      <style></style>
   </head>
   
   <body>
      <h3>First header</h3>
      <p>text text text</p>
      <div class="content">
         <h3>My Text 0<a href="https://www.google.com">The site of google</a></h3>
      </div>
      <div>
         My Text 1
         <div class="cls">My Text 2
         <h1>My Text 3</h1>
      </div>
      </div>
   </body>
   
</html>
```

**The result I want extract:**

```
<div class="content">
    <h3>My Text 0<a href="https://www.google.com">The site of google</a></h3>
</div>
```

Thanks.

**Comment by lagner** [comment]
I have just added a new method called `outerHtml`. There was no such opportunity before.
Please take a look at the *outerHtmlTest* in the *tst_qgumboparsertest.cpp* to check how it works.

Hope it helps.

**Comment by lagner** [comment]
There is no any feedback here so I guess I can close it.
